name: RAPx-booting and testing

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RAP_RECURSIVE: deep

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Code Formatting Check
      run: cd rapx && cargo fmt --check

    - name: Build RAPx 
      run: ./install.sh

    - name: Running Cargo Test
      run: cd rapx && cargo test
      
    - run: sudo apt install colorized-logs -y # Insall ansi2txt

    - name: Running Other Test Cases 
      run: cd ./rapx/tests/others && ./batch.sh -F -M -O -A